query getPublication(
  $appId: ID = "iea"
  $itemId: ID = ""
  $lang: String = "en"
) {
  getPublication(appId: $appId, itemId: $itemId, lang: $lang) {
    affiliations {
      image {
        alt
        backgroundColor
        caption
        copyright
        license
        licenseUrl
        url
      }
      location {
        alt
        city
        country
        details
        geocode {
          lat
          lng
        }
        name
        street
        zip
      }
      name
      ror
      url
    }
    color
    date
    description
    files {
      createdAt
      file
      fileType
      hash
      slug
      image {
        alt
        backgroundColor
        caption
        copyright
        license
        licenseUrl
        url
      }
      name
      path
      size
      thumb
      updatedAt
      url
    }
    gallery {
      backgroundColor
      alt
      caption
      copyright
      license
      licenseUrl
      url
    }
    image {
      alt
      backgroundColor
      caption
      copyright
      license
      licenseUrl
      url
    }
    subtitle
    tags {
      createdAt
      description
      icon
      name
      updatedAt
    }
    name
    url
    video {
      alt
      backgroundColor
      caption
      copyright
      license
      licenseUrl
      url
    }
    appId
    type
    related {
      events {
        slug
        description
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        name
        url
      }
      news {
        description
        slug
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        name
        url
      }
      people {
        firstname
        slug
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        lastname
      }
      projects {
        description
        slug
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        name
        url
      }
      publications {
        slug
        name
        url
      }
    }
    slug {
      fr
      en
    }
  }
}
