query listPublications(
  $appId: ID = "iea"
  $lang: String = "en"
  $options: ListInput = {}
) {
  listPublications(options: $options, appId: $appId, lang: $lang) {
    items {
      date
      featured
      eventCategories
      newsCategory
      type
      authors {
        firstname
        lastname
        slug
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
      }
      image {
        alt
        backgroundColor
        caption
        copyright
        license
        url
        licenseUrl
      }
      summary
      description
      name
      url
      tags {
        createdAt
        description
        name
        icon
        updatedAt
      }
      slug
    }
    total
  }
}
