query listActions(
  $options: ListInput = { skip: 0, limit: 9, sort: "nameasc", filters: "{}" }
  $appId: ID = "iea"
  $lang: String = "en"
) {
  listActions(options: $options, appId: $appId, lang: $lang) {
    items {
      color
      image {
        alt
        backgroundColor
        caption
        copyright
        license
        licenseUrl
        url
      }
      link
      name
      slots
      start
      stop
      video
      slug
    }
    total
  }
}
