query getNews($appId: ID = "iea", $itemId: ID = "", $lang: String = "en") {
  getNews(appId: $appId, itemId: $itemId, lang: $lang) {
    category
    color
    date
    description
    featured
    slug {
      fr
      en
    }
    files {
      createdAt
      file
      fileType
      hash
      slug
      image {
        alt
        caption
        backgroundColor
        copyright
        license
        licenseUrl
        url
      }
      name
      path
      size
      thumb
      updatedAt
      url
    }
    gallery {
      alt
      backgroundColor
      caption
      copyright
      license
      licenseUrl
      url
    }
    image {
      alt
      backgroundColor
      caption
      copyright
      license
      licenseUrl
      url
    }
    tags {
      createdAt
      description
      icon
      name
      updatedAt
    }
    name
    url
    appId
    related {
      events {
        description
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        name
        url
      }
      news {
        description
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        name
        url
      }
      people {
        firstname
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        lastname
      }
      projects {
        description
        name
        image {
          alt
          backgroundColor
          caption
          copyright
          license
          licenseUrl
          url
        }
        url
      }
      publications {
        name
        url
      }
    }
  }
}
