query listNews(
  $appId: ID = "iea"
  $lang: String = "en"
  $options: ListInput = {}
) {
  listNews(options: $options, appId: $appId, lang: $lang) {
    total
    items {
      slug
      summary
      category
      color
      date
      description
      featured
      image {
        alt
        backgroundColor
        caption
        copyright
        license
        licenseUrl
        url
      }
      tags {
        createdAt
        description
        icon
        name
        updatedAt
      }
      name
      url
    }
  }
}
