mutation MultipartPreSignedUrls(
  $fileKey: String!
  $fileId: String!
  $parts: Int!
) {
  multipartPreSignedUrls(fileKey: $fileKey, fileId: $fileId, parts: $parts) {
    signedUrl
    PartNumber
  }
}
