query listFiles(
  $appId: ID = "iea"
  $lang: String = "en"
  $options: ListInput = {
    skip: 0
    limit: 9
    sortBy: ["start"]
    sortDesc: false
    filters: "{}"
  }
) {
  listFiles(options: $options, appId: $appId, lang: $lang) {
    items {
      createdAt
      file
      fileType
      category
      hash
      slug
      alt
      backgroundColor
      caption
      copyright
      license
      licenseUrl
      name
      path
      size
      thumb
      updatedAt
      url
    }
    total
  }
}
