query getFile($appId: ID = "iea", $itemId: ID = "", $lang: String = "en") {
  getFile(appId: $appId, itemId: $itemId, lang: $lang) {
    alt
    backgroundColor
    caption
    category
    copyright
    createdAt
    fileType
    hash
    license
    licenseUrl
    name
    path
    size
    slug
    thumb
    updatedAt
    url
  }
}
