query listFiles(
  $appId: ID = "iea"
  $lang: String = "en"
  $options: ListInput = {
    skip: 0
    limit: 9
    sort
    filters: "{}"
  }
) {
  listFiles(options: $options, appId: $appId, lang: $lang) {
    items {
      alt
      backgroundColor
      caption
      category
      copyright
      createdAt
      fileType
      hash
      license
      licenseUrl
      name
      path
      size
      slug
      thumb
      updatedAt
      url
    }
    total
  }
}
