query listAffiliations(
  $options: ListInput = {}
  $lang: String = "en"
  $appId: ID = "iea"
) {
  listAffiliations(options: $options, appId: $appId, lang: $lang) {
    items {
      image {
        alt
        backgroundColor
        caption
        copyright
        license
        licenseUrl
        url
      }
      locations {
        alt
        city
        country
        details
        geocode {
          lat
          lng
        }
        name
        street
        zip
      }
      category
      name
      ror
      url
      slug
    }
    total
  }
}
