query listEvents(
  $options: ListInput = {}
  $appId: ID = "iea"
  $lang: String = "en"
) {
  listEvents(options: $options, appId: $appId, lang: $lang) {
    items {
      availableSlots
      bookingState
      category
      dateText
      details
      eventType
      summary
      subtitle
      image {
        alt
        backgroundColor
        caption
        copyright
        license
        licenseUrl
        url
      }
      name
      outside
      # location {
      #   address
      #   name
      #   url
      # }
      state
      start
      stop
      slug
    }
    total
  }
}
