export enum Thematics {
  AgricultureAndFood = "AGRICULTURE_AND_FOOD",
  ArtificialIntelligence = "ARTIFICIAL_INTELLIGENCE",
  CommunicationAndDigitalEconomy = "COMMUNICATION_AND_DIGITAL_ECONOMY",
  BehaviourPerceptionEmotions = "BEHAVIOUR_PERCEPTION_EMOTIONS",
  CitiesAndRegions = "CITIES_AND_REGIONS",
  CulturalHeritage = "CULTURAL_HERITAGE",
  DemocracyCitizenshipAndGovernance = "DEMOCRACY_CITIZENSHIP_AND_GOVERNANCE",
  EducationAndResearch = "EDUCATION_AND_RESEARCH",
  EnergyNaturalResources = "ENERGY_NATURAL_RESOURCES",
  EnvironmentAndClimate = "ENVIRONMENT_AND_CLIMATE",
  IdentitiesGenderAndSexualities = "IDENTITIES_GENDER_AND_SEXUALITIES",
  InequalitiesInclusionSocialInnovation = "INEQUALITIES_INCLUSION_SOCIAL_INNOVATION",
  Migrations = "MIGRATIONS",
  Oceans = "OCEANS",
  PublicPolicies = "PUBLIC_POLICIES",
  RadicalisationViolenceExtremism = "RADICALISATION_VIOLENCE_EXTREMISM",
  RegulationAndGlobalisation = "REGULATION_AND_GLOBALISATION",
  ReligionSecularismSocieties = "RELIGION_SECULARISM_SOCIETIES",
  HealthAndAgeing = "HEALTH_AND_AGEING",
  SecurityWarAndPeace = "SECURITY_WAR_AND_PEACE",
  Space = "SPACE",
  TransportMobilityTourism = "TRANSPORT_MOBILITY_TOURISM",
  WorkInnovationTechnology = "WORK_INNOVATION_TECHNOLOGY",
}
