query search(
  $appId: ID = ""
  $search: String = ""
  $lang: String = "en"
  $disciplines: [String]
) {
  search(
    appId: $appId
    search: $search
    lang: $lang
    disciplines: $disciplines
  ) {
    events {
      items {
        availableSlots
        bookingState
        category
        disciplines
        start
        status
        summary
        eventType
        slug
        name
        image {
          ...searchImage
        }
        score
      }
      total
    }
    fellowships {
      items {
        ...fellowshipItem
      }
      total
    }
    team {
      items {
        ...peopleItem
      }
      total
    }
    sab {
      items {
        ...peopleItem
      }
      total
    }
    board {
      items {
        ...peopleItem
      }
      total
    }
    ethics {
      items {
        ...peopleItem
      }
      total
    }
    fellows {
      items {
        ...peopleItem
      }
      total
    }
    initiatives {
      items {
        ...projectItem
      }
      total
    }
    tools {
      items {
        ...projectItem
      }
      total
    }
    projects {
      items {
        ...projectItem
      }
      total
    }
    media {
      items {
        ...publicationItem
      }
      total
    }
    publications {
      items {
        ...publicationItem
      }
      total
    }
    news {
      items {
        ...publicationItem
      }
      total
    }
  }
}

fragment searchImage on Image {
  alt
  backgroundColor
  caption
  copyright
  license
  licenseUrl
  url
}

fragment peopleItem on People {
  firstname
  lastname
  summary
  disciplines
  slug
  score
  image {
    ...searchImage
  }
}

fragment projectItem on Project {
  date
  featured
  name
  summary
  disciplines
  subtitle
  tags {
    name
  }
  slug
  score
  image {
    ...searchImage
  }
}

fragment publicationItem on Publication {
  disciplines
  subtitle
  name
  summary
  date
  slug
  score
  image {
    ...searchImage
  }
}

fragment fellowshipItem on Fellowship {
  applicationStart
  applicationStop
  disciplines
  fellowshipStart
  fellowshipType
  fellowshipStop
  name
  summary
  slug
  score
  image {
    ...searchImage
  }
}
