query listDisciplines(
  $appId: ID = "iea"
  $lang: String = "en"
  $options: ListInput = {
    skip: 0
    limit: 9
    sort
    filters: "{}"
  }
) {
  listDisciplines(options: $options, appId: $appId, lang: $lang) {
    items {
      createdAt
      description
      icon
      name
      updatedAt
      slug
    }
    total
  }
}
