query getMailing($appId: ID = "iea", $itemId: ID = "", $lang: String = "en") {
  getMailing(appId: $appId, itemId: $itemId, lang: $lang) {
    createdAt
    date
    description
    name
    updatedAt
    slug
  }
}
