query listMailing(
  $appId: ID = "iea"
  $lang: String = "en"
  $options: ListInput = { skip: 0, limit: 9, sort: "nameasc", filters: "{}" }
) {
  listMailing(options: $options, appId: $appId, lang: $lang) {
    items {
      createdAt
      date
      description
      name
      updatedAt
      slug
    }
    total
  }
}
