query getApp($appId: ID = "iea", $lang: String = "en") {
  getApp(appId: $appId, lang: $lang) {
    appId
    color
    date
    description
    logo {
      alt
      backgroundColor
      caption
      copyright
      license
      licenseUrl
      url
    }
    name
    state
    subtitle
    summary
    tags {
      createdAt
      description
      icon
      name
      updatedAt
    }
    url
    slug {
      fr
      en
    }
  }
}
